variables:
  project_name: 'Project001.ServiceClient.Api'
  project_test_name: 'Project001.ServiceClient.Tests'
  solution_name: 'Project001.ServiceClient'
  netcore_version: '3.1'

jobs:
- job: Build
  steps:
  - script: |
      pwd && ls -la
      dotnet restore
      dotnet publish -c Release -o bin/Release/netcoreapp$(netcore_version)
      mkdir artifact
      cp -r $(project_name)/bin/Release/netcoreapp$(netcore_version) artifact/$(Build.SourceBranchName)
    displayName: Build Application
  - task: PublishPipelineArtifact@1
    displayName: Store Application Artifact
    inputs:
      path: $(System.DefaultWorkingDirectory)/artifact
      artifact: $(project_name)
- job: UnitTests
  dependsOn: Build
  steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(project_test_name).Tests/$(project_test_name).Tests.csproj'
        testRunTitle: 'Running Unit Test'
- job: Publish
  dependsOn: UnitTests
  steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: true
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Project001.ServiceClient'